version: '2'
services:
  vasp-app:
    image: vasp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@vasp-oracle:1521:VASP
      - JHIPSTER_CACHE_MEMCACHED_SERVERS=vasp-memcached:11211
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  vasp-memcached:
    extends:
      file: memcached.yml
      service: vasp-memcached
